export const BRAND_CONFIG = {
  name: "Shreem Finserv",
  legalName: "Shreem Finserv Private Limited",
  tagline: "Your Financial Growth Partner",
  subTagline: "Instant Loan Disbursal with Minimal Paperwork",
  phone: "+91 8745003840",
  phoneDisplay: "+91 87450 03840",
  email: "Finservshreem@gmail.com",
  address: "Office No. 537, Cloud 9 Tower, Vaishali (GZB), UP 201010",
  city: "Vaishali, Ghaziabad",
  state: "Uttar Pradesh",
  pincode: "201010",
  workingHours: "Mon - Sat: 9:30 AM - 6:30 PM",
  compliance: {
    dpdp: "DPDP 2026 Compliant",
    security: "100% Secure & Encrypted",
    upfrontFee: "Zero Upfront Fees",
    rbiDisclaimer: "RBI Disclaimer: Loans are subject to credit appraisal, eligibility criteria and RBI guidelines.",
  },
  social: {
    linkedin: "https://www.linkedin.com/in/shreem-finserv-508234316",
    twitter: "",
    instagram: "https://www.instagram.com/shreemfinserv?igsi=MXFjcmRyc3Y3NTFiYQ%3D%3D&utm_source=qr",
    facebook: "",
    whatsapp: "https://wa.me/918745003840",
  },
  routes: {
    home: "/",
    doctorLoan: "/personal-loan/for-doctors",
    msmeWorkingCapital: "/business-loan/msme-working-capital",
    loanAgainstProperty: "/loan-against-property",
    machineryLoan: "/machinery-loan",
    urgentCash: "/personal-loan/urgent-cash",
    womenLoan: "/business-loan/for-women",
  },
  products: [
    {
      id: "personal-loan-doctors",
      title: "Personal & Professional Loans",
      slug: "/personal-loan/for-doctors",
      category: "Personal Loan",
      icon: "medical_services",
      shortDesc: "Collateral-free financing tailored for salaried individuals, Doctors, CAs, and Consultants.",
      maxAmount: "₹50K – ₹1Cr",
      interestRate: "From 9.9% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "Within 24 Hours",
    },
    {
      id: "msme-working-capital",
      title: "Business Loans & MSME",
      slug: "/business-loan/msme-working-capital",
      category: "Business Loan",
      icon: "storefront",
      shortDesc: "Unsecured working capital lines to manage operational cash flow, inventory, and enterprise growth.",
      maxAmount: "₹1L – upto ₹2Cr",
      interestRate: "From 10.5% p.a.",
      tenure: "Up to 5 Years",
      processingTime: "Within 48 Hours",
    },
    {
      id: "home-loan",
      title: "Home Loans",
      slug: "/home-loan",
      category: "Mortgage Loan",
      icon: "home",
      shortDesc: "Affordable home purchase, construction, renovation, and balance transfer loans at lowest interest.",
      maxAmount: "₹10L – ₹5Cr",
      interestRate: "From 8.5% p.a.",
      tenure: "Up to 30 Years",
      processingTime: "3 to 5 Days",
    },
    {
      id: "loan-against-property",
      title: "Loan Against Property",
      slug: "/loan-against-property",
      category: "Mortgage Loan",
      icon: "real_estate_agent",
      shortDesc: "Unlock substantial capital against residential, commercial, or industrial real estate.",
      maxAmount: "₹25L – ₹10Cr",
      interestRate: "From 9% p.a.",
      tenure: "Up to 15–20 Years",
      processingTime: "5 to 7 Days",
    },
    {
      id: "machinery-loan",
      title: "Machinery & Supply Chain",
      slug: "/machinery-loan",
      category: "Asset Financing",
      icon: "precision_manufacturing",
      shortDesc: "Finance plant machinery, diagnostic equipment, and supply chain invoices up to 90% funding.",
      maxAmount: "₹10L – ₹5Cr",
      interestRate: "From 10% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "3 Days",
    },
    {
      id: "urgent-cash-advance",
      title: "Urgent Cash Advance",
      slug: "/personal-loan/urgent-cash",
      category: "Personal Loan",
      icon: "bolt",
      shortDesc: "Short-term liquidity solutions for immediate, unforeseen financial and medical requirements.",
      maxAmount: "₹50K – ₹25L",
      interestRate: "From 1.15% / month",
      tenure: "3 to 24 Months",
      processingTime: "Disbursal in 2 Hours",
    },
    {
      id: "loans-for-women",
      title: "Loans for Women Entrepreneurs",
      slug: "/business-loan/for-women",
      category: "Business Loan",
      icon: "diversity_3",
      shortDesc: "Empowering female founders with subsidized credit facilities and dedicated advisory.",
      maxAmount: "₹1L – ₹75L",
      interestRate: "From 10.0% p.a. (0.5% Subsidy)",
      tenure: "Up to 5 Years",
      processingTime: "24-48 Hours",
    },
  ],
} as const;
