export const BRAND_CONFIG = {
  name: "Shreem Finserv",
  legalName: "Shreem Finserv Private Limited",
  tagline: "Your Financial Growth Partner",
  subTagline: "Instant Loan Disbursal with Minimal Paperwork",
  phone: "+91 9355445828",
  phoneDisplay: "+91 93554 45828",
  email: "Finservshreem@gmail.com",
  address: "Office No. 537, Cloud 9 Tower, Vaishali (GZB), UP 201010",
  city: "Vaishali, Ghaziabad",
  state: "Uttar Pradesh",
  pincode: "201010",
  workingHours: "Mon - Sat: 9:30 AM - 6:30 PM",
  compliance: {
    dpdp: "DPDP 2026 Compliant",
    security: "100% Secure & Encrypted",
    upfrontFee: "Zero Upfront Fees",
    rbiDisclaimer: "RBI Disclaimer: Loans are subject to credit appraisal, eligibility criteria and RBI guidelines.",
  },
  social: {
    linkedin: "",
    twitter: "",
    instagram: "",
    facebook: "",
    whatsapp: "https://wa.me/919355445828",
  },
  routes: {
    home: "/",
    doctorLoan: "/personal-loan/for-doctors",
    msmeWorkingCapital: "/business-loan/msme-working-capital",
    loanAgainstProperty: "/loan-against-property",
    machineryLoan: "/machinery-loan",
    urgentCash: "/personal-loan/urgent-cash",
    womenLoan: "/business-loan/for-women",
  },
  products: [
    {
      id: "personal-loan-doctors",
      title: "Personal Loans for Doctors",
      slug: "/personal-loan/for-doctors",
      category: "Personal Loan",
      icon: "medical_services",
      shortDesc: "Unsecured lending with preferential rates designed specifically for medical professionals.",
      maxAmount: "₹ 50,00,000",
      interestRate: "Starting 9.99% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "Within 24 Hours",
    },
    {
      id: "msme-working-capital",
      title: "MSME Working Capital",
      slug: "/business-loan/msme-working-capital",
      category: "Business Loan",
      icon: "storefront",
      shortDesc: "Flexible credit lines to manage cash flow, payroll, and operational expenses smoothly.",
      maxAmount: "₹ 2,00,00,000",
      interestRate: "Starting 11.25% p.a.",
      tenure: "12 to 60 Months",
      processingTime: "48 Hours",
    },
    {
      id: "loan-against-property",
      title: "Loan Against Property",
      slug: "/loan-against-property",
      category: "Mortgage Loan",
      icon: "real_estate_agent",
      shortDesc: "Unlock high-ticket capital against residential, commercial, or industrial real estate.",
      maxAmount: "₹ 15,00,00,000",
      interestRate: "Starting 8.75% p.a.",
      tenure: "Up to 15 Years",
      processingTime: "3 to 5 Days",
    },
    {
      id: "machinery-loan",
      title: "Machinery & Equipment",
      slug: "/machinery-loan",
      category: "Asset Financing",
      icon: "precision_manufacturing",
      shortDesc: "Upgrade plant capacity and manufacturing capabilities with dedicated machinery loans.",
      maxAmount: "₹ 5,00,00,000",
      interestRate: "Starting 10.50% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "3 Days",
    },
    {
      id: "urgent-cash-advance",
      title: "Urgent Cash Advance",
      slug: "/personal-loan/urgent-cash",
      category: "Personal Loan",
      icon: "bolt",
      shortDesc: "Short-term liquidity solutions for immediate, unforeseen financial requirements.",
      maxAmount: "₹ 5,00,00,000",
      interestRate: "Starting 1.15% / month",
      tenure: "3 to 24 Months",
      processingTime: "Disbursal in 2 Hours",
    },
    {
      id: "loans-for-women",
      title: "Loans for Women Entrepreneurs",
      slug: "/business-loan/for-women",
      category: "Business Loan",
      icon: "diversity_3",
      shortDesc: "Empowering female founders with subsidized credit facilities and dedicated advisory.",
      maxAmount: "₹ 75,00,000",
      interestRate: "Special 0.5% Concession",
      tenure: "Up to 5 Years",
      processingTime: "24-48 Hours",
    },
  ],
} as const;
