export const BRAND_CONFIG = {
  name: "Shreem Finserv",
  legalName: "Shreem Finserv Private Limited",
  tagline: "Your Financial Growth Partner",
  subTagline: "Instant Loan Disbursal with Minimal Paperwork",
  phone: "+91 8745003840",
  phoneDisplay: "+91 87450 03840",
  email: "Finservshreem@gmail.com",
  address: "Office No. 537, 5th Floor, Cloud 9, H3 Tower, Vaishali (GZB), UP 201010",
  city: "Vaishali, Ghaziabad",
  state: "Uttar Pradesh",
  pincode: "201010",
  workingHours: "Mon - Sat: 9:30 AM - 6:30 PM",
  founder: {
    name: "Shikha Gahlout",
    title: "Founder & Director, Shreem Finserv",
    quote: "One Roof. Multiple Financial Solutions. One Trusted Partner.",
    bio: "With a strong professional background spanning Software and Finance, Shikha Gahlout brings a unique combination of technology-driven thinking, financial expertise, and customer-centric approach to the financial services industry.",
  },
  googleMapsEmbedUrl: "https://maps.google.com/maps?q=Cloud%209%2C%20H3%20Tower%2C%20Vaishali%2C%20Ghaziabad%2C%20Uttar%20Pradesh%20201010&t=&z=15&ie=UTF8&iwloc=&output=embed",
  googleMapsLink: "https://maps.google.com/?q=Cloud+9+H3+Tower+Vaishali+Ghaziabad",
  compliance: {
    dpdp: "DPDP 2026 Compliant",
    security: "100% Secure & Encrypted",
    upfrontFee: "Zero Upfront Fees",
    rbiDisclaimer: "RBI Disclaimer: Loans are subject to credit appraisal, eligibility criteria and RBI guidelines.",
  },
  social: {
    linkedin: "https://www.linkedin.com/in/shreem-finserv-508234316",
    twitter: "",
    instagram: "https://www.instagram.com/shreemfinserv?igsi=MXFjcmRyc3Y3NTFiYQ%3D%3D&utm_source=qr",
    facebook: "",
    whatsapp: "https://wa.me/918745003840",
  },
  routes: {
    home: "/",
    professionalLoan: "/professional-loan",
    doctorLoan: "/professional-loan/doctor-loan",
    caLoan: "/professional-loan/ca-loan",
    businessLoan: "/business-loan",
    homeLoan: "/home-loan",
    loanAgainstProperty: "/loan-against-property",
    personalLoan: "/personal-loan",
    workingCapital: "/working-capital",
    machineryLoan: "/machinery-loan",
    carLoan: "/car-loan",
    educationLoan: "/education-loan",
  },
  products: [
    {
      id: "professional-loan",
      title: "Professional Loan",
      slug: "/professional-loan",
      category: "Professional Loan",
      icon: "medical_services",
      shortDesc: "Collateral-free high-limit financing tailored for Doctors, CAs, Architects, and Certified Professionals.",
      maxAmount: "₹1L – ₹75L",
      interestRate: "From 9.90% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "Within 24 Hours",
    },
    {
      id: "doctor-loan",
      title: "Doctor Loan",
      slug: "/professional-loan/doctor-loan",
      category: "Professional Loan",
      icon: "stethoscope",
      shortDesc: "Specialized collateral-free financing for MBBS/BDS/MD doctors to expand clinics, upgrade medical machinery & manage working capital.",
      maxAmount: "₹1L – ₹75L",
      interestRate: "From 11.99% p.a.",
      tenure: "Up to 5 Years",
      processingTime: "24-48 Hours",
    },
    {
      id: "ca-loan",
      title: "CA Loan",
      slug: "/professional-loan/ca-loan",
      category: "Professional Loan",
      icon: "calculate",
      shortDesc: "Customized collateral-free credit line for Chartered Accountants for office expansion, audit cash flows & business growth.",
      maxAmount: "₹1L – ₹75L",
      interestRate: "From 13.00% p.a.",
      tenure: "Up to 5 Years",
      processingTime: "24-48 Hours",
    },
    {
      id: "business-loan",
      title: "Business Loan",
      slug: "/business-loan",
      category: "Business Loan",
      icon: "storefront",
      shortDesc: "Collateral-free commercial credit lines to manage operational cash flow, inventory, and enterprise growth.",
      maxAmount: "₹1L – ₹2Cr",
      interestRate: "From 14.00% p.a.",
      tenure: "Up to 5 Years",
      processingTime: "Within 48 Hours",
    },
    {
      id: "home-loan",
      title: "Home Loan",
      slug: "/home-loan",
      category: "Mortgage Loan",
      icon: "home",
      shortDesc: "Affordable home purchase, construction, renovation, and balance transfer loans at lowest interest.",
      maxAmount: "₹10L – ₹5Cr",
      interestRate: "From 7.25% p.a.",
      tenure: "Up to 30 Years",
      processingTime: "3 to 5 Days",
    },
    {
      id: "loan-against-property",
      title: "Loan Against Property",
      slug: "/loan-against-property",
      category: "Mortgage Loan",
      icon: "real_estate_agent",
      shortDesc: "Unlock substantial capital against residential, commercial, or industrial real estate.",
      maxAmount: "₹25L – ₹10Cr",
      interestRate: "From 9.00% p.a.",
      tenure: "Up to 15–20 Years",
      processingTime: "5 to 7 Days",
    },
    {
      id: "personal-loan",
      title: "Personal Loan",
      slug: "/personal-loan",
      category: "Personal Loan",
      icon: "payments",
      shortDesc: "Instant multi-purpose personal credit for medical needs, debt consolidation, and personal commitments.",
      maxAmount: "₹50K – ₹40L",
      interestRate: "From 10.50% p.a.",
      tenure: "1 to 5 Years",
      processingTime: "Instant / Same Day",
    },
    {
      id: "working-capital",
      title: "Working Capital Loan",
      slug: "/working-capital",
      category: "Business Loan",
      icon: "account_balance_wallet",
      shortDesc: "Revolving credit lines and overdraft facilities to maintain liquid operational cash flows.",
      maxAmount: "₹5L – ₹2Cr",
      interestRate: "From 14.00% p.a.",
      tenure: "12 to 36 Months",
      processingTime: "Within 48 Hours",
    },
    {
      id: "car-loan",
      title: "Car Loan",
      slug: "/car-loan",
      category: "Vehicle Loan",
      icon: "directions_car",
      shortDesc: "Finance new or certified pre-owned four-wheelers with up to 80% on-road funding for new cars and competitive rates.",
      maxAmount: "₹1L – ₹1Cr",
      interestRate: "From 7.50% p.a.",
      tenure: "Up to 8 Years",
      processingTime: "Within 24 Hours",
    },
    {
      id: "education-loan",
      title: "Education Loan",
      slug: "/education-loan",
      category: "Education Financing",
      icon: "school",
      shortDesc: "Fund higher education in premier Indian institutes and top overseas universities with flexible tenures.",
      maxAmount: "₹2L – ₹1.5Cr",
      interestRate: "From 8.50% p.a.",
      tenure: "Up to 15 Years",
      processingTime: "2 to 3 Days",
    },
    {
      id: "machinery-loan",
      title: "Machinery & Equipment Loan",
      slug: "/machinery-loan",
      category: "Asset Financing",
      icon: "precision_manufacturing",
      shortDesc: "Finance plant machinery, diagnostic equipment, and supply chain invoices up to 90% funding.",
      maxAmount: "₹10L – ₹5Cr",
      interestRate: "From 10.00% p.a.",
      tenure: "Up to 7 Years",
      processingTime: "3 Days",
    },
  ],
} as const;
